### ISSUE TITLE
校园网IPV6免流方案（国内直连免流） | Wherelse Blog

### ISSUE THREAD

**Issue by wherelse** [wherelse/wherelse.github.io#4]
https://www.wherelse.tk/post/dai-tou-ming-dai-li-de-xiao-yuan-wang-ipv6-mian-liu-fang-an-guo-nei-zhi-lian-mian-liu/ 

 在折腾的路上越走越远

**Comment by zhenhuizhang** [comment]
**校园局域网**大标题已经写好啦，坐等更新哈哈哈
